name: Conformance

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  conformance:
    uses: trsdn/.github/.github/workflows/conformance.yml@main
